# Generated by Django 4.0 on 2022-08-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('rentamount', models.IntegerField()),
                ('purpose', models.CharField(max_length=50)),
                ('bathno', models.IntegerField()),
                ('furnishingStatus', models.CharField(max_length=50)),
                ('housetype', models.CharField(max_length=50)),
                ('rentFrequency', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('roomnumber', models.IntegerField()),
            ],
        ),
    ]
