# Generated by Django 4.0 on 2022-10-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forrent',
            name='amenities',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forsale',
            name='amenities',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
