# Generated by Django 4.0 on 2022-11-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_forrent_amenities_forsale_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forrent',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realtor.contacts'),
        ),
        migrations.AlterField(
            model_name='forsale',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realtor.contacts'),
        ),
    ]
