# Generated by Django 4.0 on 2022-08-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_rename_image_data_image_one_alter_data_bathno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image_one',
            field=models.ImageField(blank='false', null='false', upload_to='uploads/images'),
        ),
    ]
