# Generated by Django 4.0 on 2022-10-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_remove_propertyowner_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
