# Generated by Django 4.0 on 2022-10-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0003_alter_contacts_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phoneNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
