# Generated by Django 4.0 on 2022-11-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0003_alter_forrent_owner_alter_forsale_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forsale',
            old_name='owner',
            new_name='ownerId',
        ),
    ]
