# Generated by Django 4.0 on 2022-08-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0004_rename_image_one_data_coverphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('coverPhoto', models.ImageField(blank='false', null='false', upload_to='uploads/images')),
                ('rentamount', models.IntegerField(blank=True)),
                ('purpose', models.CharField(max_length=50)),
                ('bathno', models.IntegerField(blank=True)),
                ('furnishingStatus', models.CharField(max_length=50)),
                ('housetype', models.CharField(max_length=50)),
                ('rentFrequency', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('roomnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('coverPhoto', models.ImageField(blank='false', null='false', upload_to='uploads/images')),
                ('price', models.IntegerField(blank=True)),
                ('purpose', models.CharField(max_length=50)),
                ('bathno', models.IntegerField(blank=True)),
                ('furnishingStatus', models.CharField(max_length=50)),
                ('housetype', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('roomnumber', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
