# Generated by Django 4.0 on 2022-08-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0005_forrent_forsale_delete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='forrent',
            name='coverPhoto1',
            field=models.ImageField(blank='true', upload_to='uploads/images'),
        ),
    ]
