# Generated by Django 4.0 on 2022-11-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0005_rename_firstname_contacts_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyowner',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='forrent',
            name='owner',
        ),
        migrations.AddField(
            model_name='forrent',
            name='ownerId',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forsale',
            name='ownerId',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='PropertyOwner',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
