# Generated by Django 4.0 on 2022-08-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0006_forrent_coverphoto1'),
    ]

    operations = [
        migrations.AddField(
            model_name='forsale',
            name='photos',
            field=models.ImageField(blank='false', null='false', upload_to='', verbose_name='uploads/images'),
            preserve_default='false',
        ),
    ]
