# Generated by Django 4.0 on 2022-11-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0006_remove_propertyowner_contact_remove_tenant_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forrent',
            old_name='photos',
            new_name='otherPhotos',
        ),
        migrations.RenameField(
            model_name='forsale',
            old_name='photos',
            new_name='otherPhotos',
        ),
    ]
